### PR TITLE
iPhone ClipboardPlugin

### PR DESCRIPTION
**Pull request by michaelkamphausen**
I added support for retrieving text from the general pasteboard to the ClipboardPlugin.

### CODE REVIEW

**Comment by benbrown** [comment]
You are awesome. I will be using this!

I hope it gets pulled into the main branch soon!

**Comment by shazron** [comment]
Well it already has at http://github.com/phonegap/phonegap-plugins - many ppl send a pull request here thinking it's the main repo

**Comment by benbrown** [comment]
Duh! Thanks!!!

## 

Ben Brown
/\* I am a software designer and online community pioneer. 
Learn more about what I do at http://XOXCO.com & http://PEOPLEPODS.net
and learn more about me at http://BENBROWN.com. */

**Comment by benbrown** [comment]
Ah, actually, it doesn't appear that this has been merged into the official one which still doesn't support getting the clipboard text.

**Comment by michaelkamphausen** [comment]
Ok, I see, so that's the reason you haven't pulled it. I tested and updated my changes today so it works with the Xcode 4 changes. I will do a pull request at http://github.com/phonegap/phonegap-plugins. Thanks for your comments!

**Pull request closed without merging**
